package PanelPages;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

public class HomePage {

    @FindBy(id = "com.qolsys:id/t3_home_iv_SensorStatus")
    public WebElement Sensor_status_bypass;
    @FindBy(id = "com.qolsys:id/message")
    public WebElement Message;
    @FindBy(id = "com.qolsys:id/t3_img_disarm")
    public WebElement DISARM;
    @FindBy(id = "com.qolsys:id/main")
    public WebElement DISARM_from_away;
    @FindBy(id = "com.qolsys:id/img_arm_stay")
    public WebElement ARM_STAY;
    @FindBy(xpath = "//android.widget.TextView[@text='ARMED STAY']")
    public WebElement ARM_STAY_text;
    @FindBy(id = "com.qolsys:id/img_arm_away")
    public WebElement ARM_AWAY;
    @FindBy(xpath = "//android.widget.TextView[@text='ARMED AWAY']")
    public WebElement ARM_AWAY_text;
    @FindBy(xpath = "//*[contains(text(), 'Arming')]")
    public WebElement Countdown;
    @FindBy(id = "com.qolsys:id/img_weather")
    public WebElement Weather_img;
    @FindBy(id = "com.qolsys:id/text_high_temp")
    public WebElement High_temp;
    @FindBy(id = "com.qolsys:id/text_low_temp")
    public WebElement Low_temp;
    @FindBy(id = "com.qolsys:id/text_time")
    public WebElement Time;
    @FindBy(id = "com.qolsys:id/text_date")
    public WebElement Date;
    @FindBy(id = "com.qolsys:id/img_contact_us")
    public WebElement Contact_Us;
    @FindBy(id = "com.qolsys:id/uiTab_active")
    public WebElement Active_Tab;
    @FindBy(id = "com.qolsys:id/uiTab_all")
    public WebElement All_Tab;
    @FindBy(id = "com.qolsys:id/t3_open_tv_active")
    public WebElement Active_Tab_expand;
    @FindBy(id = "com.qolsys:id/t3_open_tv_all")
    public WebElement All_Tab_expand;
    @FindBy(id = "com.qolsys:id/t3_emergency_icon")
    public WebElement Emergency_Button;
    @FindBy(id = "com.qolsys:id/t3_tv_disarm")
    public WebElement Disarmed_text;
    @FindBy(id = "com.qolsys:id/tvSystemStatus")
    public WebElement System_status;
    @FindBy(id = "com.qolsys:id/img_expand")
    public WebElement System_state_expand;
    @FindBy(id = "com.qolsys:id/img_collapse")
    public WebElement System_state_collapse;
    @FindBy(id = "com.qolsys:id/uiExitSoundText")
    public WebElement Exit_Sounds_title;
    @FindBy(id = "com.qolsys:id/img_exit_sound")
    public WebElement Exit_Sounds;
    @FindBy(id = "com.qolsys:id/uiExitSoundValue")
    public WebElement Exit_Sounds_value;
    @FindBy(id = "com.qolsys:id/uiEntryDelayText")
    public WebElement Entry_Delay_title;
    @FindBy(id = "com.qolsys:id/img_entry_delay")
    public WebElement Entry_Delay;
    @FindBy(id = "com.qolsys:id/entryDelayTvValue")
    public WebElement Entry_Delay_value;
    @FindBy(id = "com.qolsys:id/tv_bypass")
    public WebElement Bypass_Tab;
    @FindBy(id = "com.qolsys:id/viewFlipper")
    public WebElement PhotoFrame_Mode;
    @FindBy(id = "com.qolsys:id/t3_img_disarm")
    public WebElement ArwAway_State;
    @FindBy(id = "com.qolsys:id/txt_title")
    public WebElement ALARM;
    @FindBy(id = "com.qolsys:id/tv_keyOne")
    public WebElement One;
    @FindBy(id = "com.qolsys:id/tv_keyTwo")
    public WebElement Two;
    @FindBy(id = "com.qolsys:id/tv_keyThree")
    public WebElement Three;
    @FindBy(id = "com.qolsys:id/tv_keyFour")
    public WebElement Four;
    @FindBy(id = "com.qolsys:id/tv_keyFive")
    public WebElement Five;
    @FindBy(id = "com.qolsys:id/tv_keySix")
    public WebElement Six;
    @FindBy(id = "com.qolsys:id/tv_keyEight")
    public WebElement Eight;
    @FindBy(id = "com.qolsys:id/tv_keyNine")
    public WebElement Nine;
    @FindBy(id = "com.qolsys:id/tv_zero")
    public WebElement Zero;
    @FindBy(id = "com.qolsys:id/tv_name")
    public WebElement Red_banner_sensor_name;
    @FindBy(id = "com.qolsys:id/tv_status")
    public WebElement Red_banner_sensor_status;
    @FindBy(xpath = "//android.widget.TextView[@text='Open Sensor']")
    public WebElement Bypass_message;
    @FindBy(id = "com.qolsys:id/cancel")
    public WebElement Bypass_Cancel;
    @FindBy(id = "com.qolsys:id/ok")
    public WebElement Bypass_OK;
    @FindBy(id = "com.qolsys:id/txt_title")
    public WebElement Enter_Code_to_Access_the_Area;
    @FindBy(id = "com.qolsys:id/ft_back")
    public WebElement Back_button;
    @FindBy(id = "com.qolsys:id/ft_emergency")
    public WebElement Emergency_button;
    @FindBy(id = "com.qolsys:id/ft_home_button")
    public WebElement Home_button;
    @FindBy(id = "com.qolsys:id/t3_home_iv_SensorStatus")
    public WebElement Tamper_Status;
    @FindBy(id = "com.qolsys:id/img_quick_exit")
    public WebElement Quick_exit;
    @FindBy(id = "com.qolsys:id/tv_fire_title")
    public WebElement Fire_Alarm;
    @FindBy(id = "com.qolsys:id/tv_police_title")
    public WebElement police_Alarm;
    @FindBy(id = "com.qolsys:id/tv_medical_title")
    public WebElement Aux_Alarm;
    @FindBy(id = "com.qolsys:id/tv_img_action_text")
    public WebElement panel_Alarm;
    @FindBy(id = "com.qolsys:id/disarmFullView")
    public WebElement System_Disarmed_State;
    @FindBy(id = "com.qolsys:id/partitionName")
    public WebElement Partition_Name;
    @FindBy(id = "com.qolsys:id/tv_keyFive")
    public WebElement pinpad;
}
